# Use a base image with a more advanced version of Python
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the necessary files into the container
COPY mnist_service.proto .
COPY mnist_service_pb2.py .
COPY mnist_service_pb2_grpc.py .
COPY mnist_service_server.py .

# Install gRPC dependencies
RUN pip install grpcio

# Expose the port on which the server will run
EXPOSE 50051

# Command to run the server
CMD ["python", "mnist_service_server.py"]
